services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scheduler
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
    container_name: backend_container
    environment:
      DATABASE_URI: postgresql://postgres:postgres@db:5432/scheduler
      DB_HOST: db
      CORS_ORIGINS: http://frontend:3000
      SECRET_KEY: "dev-secret"
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      PORT: "5000"
      URL: "http://localhost:5050"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - "5050:5000"
    volumes:
      - ./client_secret.json:/proyect/client_secret.json:ro
    restart: unless-stopped
